Importing libaries

In [220]:
import os
import re
import nltk
import string
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer


<h1>load data<h1>

In [221]:
data=pd.read_csv('Data.csv')
data

Text Language
0       Nature, in the broadest sense, is the natural...  English
1      "Nature" can refer to the phenomena of the phy...  English
2      The study of nature is a large, if not the onl...  English
3      Although humans are part of nature, human acti...  English
4      [1] The word nature is borrowed from the Old F...  English
...                                                  ...      ...
10332  ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...  Kannada
10333  ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...  Kannada
10334  ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...  Kannada
10335  ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...  Kannada
10336  ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...  Kannada

[10337 rows x 2 columns]

In [222]:
data.head()

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [223]:
data.tail()

Text Language
10332  ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...  Kannada
10333  ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...  Kannada
10334  ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...  Kannada
10335  ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...  Kannada
10336  ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...  Kannada

In [224]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Text      10337 non-null  object
 1   Language  10337 non-null  object
dtypes: object(2)
memory usage: 161.6+ KB


In [225]:
data.Language.value_counts()

English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: Language, dtype: int64

In [226]:
data.drop(data[data.duplicated()].index, axis=0, inplace=True)

<h2>Separating features

In [227]:

X = data['Text']
y = data['Language']

<h2>Text Preprocessing

In [228]:
clean_data=[]
def cleaner(x):
  x = re.sub(r'[\([{})\]!@#$,"%^*?:;~`]', ' ', x)
  x = re.sub(r"\\|[0-9]|/|-|_|'|\.", '', x)
  x = re.sub('\s+', ' ', x)  
  x = x.lower()
  return x

data['Text'] = data['Text'].map(cleaner)

<h2>Label Encoding

In [230]:

le=LabelEncoder()
y=le.fit_transform(data["Language"].to_numpy())

<h2>CountVectorizer words

In [231]:
cv=CountVectorizer()
X=cv.fit_transform(data['Text'])

In [233]:
X.shape

(10271, 40164)

<h2>Cross validation

In [234]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=42)

<h1>Creting models 

<h2>create first model 

In [235]:
f_model=MultinomialNB()
f_model.fit(X_train, y_train)

MultinomialNB()

In [236]:
y_pred=f_model.predict(X_test)

In [237]:
acc=accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
print(f'ACcuracy={acc:.3f}')
print("confusion_matrix is :","\n",cm)

ACcuracy=0.981
confusion_matrix is : 
 [[144   0   0   2   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  98   0   3   0   0   0   0   0   0   0   0   0   0   2   0   0]
 [  0   0 128   4   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 361   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   3 252   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   1   0 113   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  78   0   0   0   0   0   1   0   0   0   0]
 [  0   0   0   1   0   0   0  11   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2   0   0   0   0 155   0   0   1   0   1   0   0   0]
 [  0   0   0   1   0   0   0   0   0  85   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0 160   0   0   0   0   0   0]
 [  0   0   0   4   0   0   0   0   0   0   0 174   0   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0   0   0   0 148   0   0   0   0]
 [  0   0   0   3   0   0   0   0   0 

<h2>Create second model 

In [238]:
s_model=RandomForestClassifier()
s_model.fit(X_train, y_train)

RandomForestClassifier()

In [239]:
y_pred=s_model.predict(X_test)

In [240]:
acc=accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
print(f'ACcuracy={acc:.3f}')
print("confusion_matrix is :","\n",cm)

ACcuracy=0.925
confusion_matrix is : 
 [[132   0   0   1   0   0   0   0   0  13   0   0   0   0   0   0   0]
 [  0  92   0   1   0   0   0   0   0   5   0   0   0   0   5   0   0]
 [  0   0 119   0   1   1   0   0   1   7   0   0   0   3   1   0   0]
 [  0   0   0 352   0   0   0   0   0   6   0   0   0   2   1   0   0]
 [  0   0   2   1 235   0   0   0   3  11   0   0   0   3   0   0   0]
 [  0   1   0   0   1 102   0   0   0  10   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  73   0   0   6   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  11   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   1   0   0 144   8   0   1   0   5   0   0   0]
 [  0   0   0   0   0   0   0   0   0  86   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  11 150   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   6   0 166   0   5   0   0   0]
 [  0   0   0   0   0   0   0   0   0  11   0   0 139   0   0   0   0]
 [  0   0   0   1   1   0   0   0   2 

<h2>Crete third Model

In [241]:
th_model=KNeighborsClassifier()
th_model.fit(X_train, y_train)

KNeighborsClassifier()

In [242]:
y_pred=th_model.predict(X_test)

In [243]:
acc=accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
print(f'ACcuracy={acc:.3f}')
print("confusion_matrix is :","\n",cm)

ACcuracy=0.523
confusion_matrix is : 
 [[ 55   0   0   0   0   0   0   0   0  79   5   0   1   0   0   6   0]
 [  1  57   0   1   0   0   0   0   0  38   3   0   1   0   0   2   0]
 [  2   1  62   0   2   1   0   0   1  48   0   1   3   5   0   7   0]
 [  5   1   5 203   1   5   0   0   0 113   2   1   3   1   0  21   0]
 [  5   1   1   1 146   0   0   0   1  68   2   6   4  11   0   9   0]
 [  3   0   0   0   0  50   0   0   0  51   0   0   0   0   0  10   0]
 [  3   0   0   0   0   0  39   0   0  31   1   0   0   0   0   5   0]
 [  0   0   0   0   0   0   0   4   0   8   0   0   0   0   0   0   0]
 [  3   0   0   0   1   2   0   0  70  72   1   0   0   2   0   8   0]
 [  0   0   0   0   0   0   0   0   0  86   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0  35 121   0   2   0   0   2   0]
 [  5   0   0   2   0   0   0   0   1  61   2  91   0   6   0  10   0]
 [  8   0   0   0   0   0   0   0   0  86   0   0  44   0   0  12   0]
 [  8   0   5   1   9   1   0   0   1 

<h3> the Best Accuracy in the first modele 

In [245]:
def prediction(text):
  x = cv.transform([text]).toarray()
  lang = f_model.predict(x)
  lang = le.inverse_transform(lang)
  print('The Language is in', lang[0])

In [254]:
prediction(" انا احب اللغه هيام ")

The Language is in Arabic


In [274]:
prediction("അനലിറ്റിക്സ്, ഡാറ്റാ സയൻസ് പ്രൊഫഷണലുകൾക്കായി കമ്മ്യൂണിറ്റി അധിഷ്ഠിത വിജ്ഞാന പോർട്ടൽ അനലിറ്റിക്സ് വിദ്യ നൽകുന്നു")


The Language is in Malayalam


In [275]:
prediction('amo la Pnl')

The Language is in Spanish
